# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Vatsal Limbachia
description: >- # this means to ignore newlines until "baseurl:"
  Vatsal Limbachia's personal website
baseurl: "" # the subpath of the site
url: "https://renaissancenerd.github.io" # the base hostname & protocol for the site
og_image: /assets/img/newton.jpeg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Publications
      slug: /publications
    - name: Blog
      slug: /blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: vkonit079@gmail.com
      link: mailto:vkonit079@gmail.com
  follow:
    - name: GitHub
      link: http://github.com/renaissancenerd

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
